plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.41.git.20230327.hash-de5c96f.cjs
